frequency: 50  # 处理频率 50Hz
two_d_mode: false  # 室外有坡度，所以不开 2D 模式
map_frame: map
odom_frame: odom
base_link_frame: base_link

# FastLIO 里程计（短时间高精度）
odom0: /Odometry
odom0_config: [false, false, false,   # 不用 FastLIO 提供的 X, Y, Z 位置
               true, true, true,     # 使用 FastLIO 角速度
               true, true, true,     # 使用 FastLIO 线速度
               true, true, true]     # 使用 FastLIO 的 Roll, Pitch, Yaw 角

# RTK 里程计（全局参考）
odom1: /fixposition/odometry_enu
odom1_config: [true, true, true,   # 用 RTK 提供的 X, Y, Z 位置
               false, false, false, # 不用 RTK 提供的角速度
               false, false, false, # 不用 RTK 提供的线速度
               false, false, false] # 不用 RTK 提供的姿态角

